/**
* Build Version Header File

* Generated by BuildInc
* Written March 2006
* By Matt Rudder (http://www.mattrudder.com)
*/

#define VERSION_MAJOR 0
#define VERSION_MINOR 3
#define VERSION_BUILD 4
#define VERSION_SPECIAL 0
#define VERSION 0,3,4,0
#define STRVERSION "0.3.4.0\0"
#define STRVERSION_EXTERNAL "0.3"
#define STRVERSION_INTERNAL "0.3 Build 4"
