/**
* @file SoundTypes.h
* @author Tom Williams
* @date Created April 26, 2006
*
* Defines the sound type ids for all sounds within the game.
*/

#ifndef _SOUNDTYPES_H_
#define _SOUNDTYPES_H_

//! List of all sounds found within the game
enum ESoundType
{
	//***  Add music at bottom of this section  **//
	SND_MUSIC_MAINMENU,
	SND_MUSIC_GAME,
	SND_MUSIC_AWESOMETIME,
	SND_MUSIC_PAUSE,
	//********************************************//

	SND_NUM_MUSIC_TRACKS,
	SND_FIRST_EFFECT = SND_NUM_MUSIC_TRACKS,

	//***  Add effects at bottom of this section  **//
	SND_EFFECT_ROCKETLAUNCH = SND_FIRST_EFFECT,
	SND_EFFECT_PLAYERRUN,
	SND_EFFECT_DEATH,
	SND_EFFECT_MENUCLICK,
	SND_EFFECT_MENUCANCEL,
	SND_EFFECT_MENUHOVER,
	SND_EFFECT_AWESOMETIME,

	// Gun Selections
	//********************************************//
	SND_SELECT_SHOTGUN,
	SND_SELECT_TIPLESHOTGUN,
	SND_SELECT_POTATOCHAINGUN,
	SND_SELECT_HOLYWATERBALLOONBATMAN,
	SND_SELECT_ROCKETLAUNCHER,
	SND_SELECT_DEAGLE,
	SND_SELECT_BIGCLUCKINGBOMB,
	//**********************************************//

	// Voices
	//**********************************************//
	SND_EFFECT_BIGCLUCKINGBOMB_MOVE,
	SND_EFFECT_BIGCLUCKINGBOMB_EXPLODE,
	SND_EFFECT_GASEOUS_READY,
	SND_EFFECT_GUNCOCK,
	SND_EFFECT_IHATEZOMBIES,
	SND_EFFECT_NEEDCASH,
	SND_EFFECT_NOTENOUGHCASH,
	SND_EFFECT_SODAWITHSHOTGUN,
	SND_EFFECT_JOHNNYTAKEDAMAGE,
	SND_EFFECT_JOHNNYTAKEDAMAGE1,
	SND_EFFECT_JOHNNYTAKEDAMAGE2,
	SND_EFFECT_JOHNNYTHROW,
	SND_EFFECT_ZOMBIEATTACK,
	SND_EFFECT_ZOMBIEBRAINS,
	SND_EFFECT_ZOMBIEDEATH,
	SND_EFFECT_ZOMBIEDEATH1,
	SND_EFFECT_ZOMBIEDEATH2,
	SND_EFFECT_ZOMBIEDEATH3,
	SND_EFFECT_ZOMBIEDEATH4,
	SND_EFFECT_ZOMBIEDEATH5,
	SND_EFFECT_ZOMBIESPAWN,
	SND_EFFECT_ZOMBIETAKEDAMAGE,
	SND_EFFECT_EXPLOSION,
	SND_EFFECT_EXPLOSION1,
	SND_EFFECT_EXPLOSION2,
	SND_EFFECT_EXPLOSION3,
	SND_EFFECT_PISTOLFIRE,
	SND_EFFECT_SHOTGUNFIRE,
	SND_EFFECT_POTATOFIRE,
	SND_EFFECT_WATERCANNONFIRE,
	//**********************************************//

	// total number of effect tracks
	SND_TOTAL_NUMBER,
};

#endif